# For full config options, check the docs:
#    docs.serverless.com
custom:
  secrets: ${file(secrets.json)}

service: hadzibot
app: hadzibot
org: msmrkovic

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: production
  environment:
    TG_BOT_TOKEN: ${self:custom.secrets.TG_BOT_TOKEN}
    API_URL: ${self:custom.secrets.API_URL}
    REZIJA_ID: ${self:custom.secrets.REZIJA_ID}
    HADZIBRAVA_ID: ${self:custom.secrets.HADZIBRAVA_ID}

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: ${self:custom.secrets.TG_BOT_TOKEN}
          method: post
          cors: true

  set-webhook:
    handler: handler.setWebhook
    events:
      - http:
          path: setWebhook
          method: post
          cors: true
